# Generated by Django 3.1.7 on 2023-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=127)),
                ('FuelType', models.CharField(default='Petrol', max_length=127)),
                ('PhotoLink', models.TextField(default='/')),
                ('Acceleration', models.CharField(default='10.10 sec', max_length=127)),
                ('TopSpeed', models.CharField(default='200 mph', max_length=127)),
                ('TotalPower', models.CharField(default='200 hp', max_length=127)),
                ('TotalTorque', models.CharField(default='200 nm', max_length=127)),
                ('Drive', models.CharField(default='AWD', max_length=127)),
                ('CarBody', models.CharField(default='Sport', max_length=127)),
                ('FeulEconomy', models.CharField(default='16', max_length=127)),
            ],
        ),
    ]
