# Generated by Django 3.1.7 on 2023-05-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Cars',
        ),
    ]
